version: "2.3"
services:
  gateway:
    build:
      context: .
      dockerfile: ./docker/images/gateway/Dockerfile
    image: practice-hooma-gateway:latest
    expose:
      - 3000
    ports:
      - "80:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      main: { }
    restart: "always"

networks:
  main:
    name: main
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.111.0.0/29
          gateway: 10.111.0.1
