version: "3.3"
services:
  gateway:
    build:
      context: "${HOOMA_API_GATEWAY_BASE_PATH:-$PWD}"
      dockerfile: "./docker/images/gateway/Dockerfile"
    image: practice-hooma-gateway:latest
    expose:
      - 3000
    ports:
      - "80:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: "always"
